### DISCUSSION TITLE
Issue Starting Fail2Ban with Dynamic Container Log Path via Script

### DISCUSSION THREAD

**Discussion by karola-gr** [fail2ban/fail2ban#3884] [Q&A]
Hi everyone,

I’m new to using Fail2Ban, especially in a Docker environment, and I’ve encountered an issue that I can’t seem to solve alone. I’d greatly appreciate your help or guidance!

What I’m Trying to Achieve

I want to configure Fail2Ban to monitor the logs of one specific Docker container, identified dynamically at runtime. The goal is:
	1.	To avoid monitoring all Docker logs on the host (e.g., /var/lib/docker/containers/*).
	2.	To dynamically update the log path (logpath) in jail.local whenever the container restarts, as the container ID is not known in advance.

To accomplish this, I’ve created a script that:
	1.	Finds the relevant container based on a label.
	2.	Extracts the log path and port dynamically.
	3.	Updates the jail.local file with the appropriate logpath and port values.
	4.	Starts the Fail2Ban server.

What Doesn’t Work

When I try to integrate my script as the Docker container’s entrypoint, Fail2Ban fails with an error. Here’s the entrypoint I’m using in docker-compose.yml:

``` entrypoint: ["/bin/bash", "/config/fail2ban/fail2ban_start.sh"] ```
On ```exec fail2ban-server -xf start ```I get en error 
```Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running? ```

If I am using static port and path in my jail.local without the script and an entry point, everything works as expected.

My Questions

	1.	Is my approach (using a script to dynamically set logpath and port) the correct way to solve this problem?
	2.	Why might Fail2Ban fail to create or access the socket when started via the script, but work fine when started directly?
	3.	Is there a better or more idiomatic way to achieve this?
	
	
Additional Context

Here’s a snippet of my script...I get the same error if the script only has the line ```exec fail2ban-server -xf start```

```
#!/bin/bash

# Extract log path and port dynamically
CONTAINER_DIR="/var/lib/docker/containers"
for config in "$CONTAINER_DIR"/*/config.v2.json; do
  LABEL=$(jq -r '.Config.Labels["label"]' "$config")
  if [[ "$LABEL" == "true" ]]; then
    LOG_PATH=$(jq -r '.LogPath' "$config")
    PORT=$(jq -r '.NetworkSettings.Ports["8081/tcp"][0].HostPort' "$config")

    sed -e "s|<LOGPATH>|$LOG_PATH|" -e "s|<PORT>|$PORT|" \
        /config/fail2ban/template.jail.local > /config/fail2ban/jail.local
    break
  fi
done

# Start Fail2Ban
exec fail2ban-server -xf start
```

My jail.local snippet 
```
[request_by_ip]
enabled = true
filter = app
action = iptables-multiport[name=app, port="<PORT>", protocol=tcp, chain=DOCKER-USER]
logpath = <LOGPATH>
maxretry = 50
findtime = 1
bantime = 300

```

And my docker compose snippet

```
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    entrypoint: ["/bin/bash", "/config/fail2ban/fail2ban_start.sh"]
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - ./fail2ban_start.sh:/config/fail2ban/fail2ban_start.sh
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./fail2ban/config/fail2ban.local:/config/fail2ban.local
      - ./fail2ban/config/jail.local:/config/fail2ban/jail.local
      - ./fail2ban/config/app.conf:/config/fail2ban/filter.d/app.conf
      - ./fail2ban/config/request_invalid_route.conf:/config/fail2ban/filter.d/request_invalid_route.conf
      - fail2ban_log:/config/log
      - /var/run:/var/run
 
     ```
