### ISSUE TITLE
Simple rules for firewalld

### ISSUE THREAD

**Issue by sedstr** [fail2ban/fail2ban#2089]
I've been struggling with fail2ban. I just want a very simple ban solution.

CentOS Linux release 7.4.1708 (Core)
fail2ban-server-0.9.7-1.el7.noarch
fail2ban-firewalld-0.9.7-1.el7.noarch
firewalld-0.4.4.4-6.el7.noarch

1. If anything is detected, on any open port (or even closed port) I want to drop any connections from those IPs for a duration. say 4 hours.
2. After any unban, if they get banned 2 more times (3 bans in total), I want to drop their connections for at least a month.
3. I want the bans to be persistent, no unbanning on shutdown, a simple test if the IP exists, in a single pass on startup, and the addition of any IPs not found in that single pass.

What I am getting is 8GB of RAM used, ssh bans not being passed cleanly to recidive, and IPs being unbanned, even though they were banned by recidive. Firewalld complaining about the same IP being added to multiple zones.

Yes, I've applied a custom jail.local.
`
[DEFAULT]
ignoreip = 127.0.0.1/8 myrange/26 myip2 myip3
findtime = 604800
bantime = 21600
maxretry = 3
usedns = no
banaction = firewallcmd-custom

[sshd]
enabled = true
filter = sshd
banaction = firewallcmd-custom-sshd
action = %(banaction)s

[postfix-sasl]
enabled = true
filter = postfix
banaction = firewallcmd-custom-postfix-sasl
action = %(banaction)s

[postfix-rbl]
enabled = true
filter = postfix
banaction = firewallcmd-custom-postfix-rbl
action = %(banaction)s

[dovecot]
enabled = true
filter = dovecot
banaction = firewallcmd-custom-dovecot
action = %(banaction)s

[recidive]
enabled = true
findtime = 604800 ; 7 day
bantime = -1 ; 7889238 3 month
maxretry = 2
banaction = firewallcmd-custom-recidive
action = %(banaction)s
`

Yes I've applied custom actions...
`
cat /etc/fail2ban/action.d/firewallcmd-custom-sshd.conf
[INCLUDES]
before  =

[Definition]

#actionban = firewall-cmd --change-source=<ip> --zone=drop2 && firewall-cmd --change-source=<ip> --zone=drop2 --permanent
#actionunban = firewall-cmd --remove-source=<ip> --zone=drop2 && firewall-cmd --remove-source=<ip> --zone=drop2 --permanent

actionban = firewall-cmd --change-source=<ip> --zone=drop
actionunban = firewall-cmd --remove-source=<ip> --zone=drop

[Init]
`
`
cat /etc/fail2ban/action.d/firewallcmd-custom-recidive.conf
[INCLUDES]
before  =

[Definition]

#actionban = firewall-cmd --change-source=<ip> --zone=drop2 && firewall-cmd --change-source=<ip> --zone=drop2 --permanent
#actionunban = firewall-cmd --remove-source=<ip> --zone=drop2 && firewall-cmd --remove-source=<ip> --zone=drop2 --permanent

actionban = firewall-cmd --change-source=<ip> --zone=recidive && firewall-cmd --runtime-to-permanent
actionunban = firewall-cmd --remove-source=<ip> --zone=recidive && firewall-cmd --runtime-to-permanent

[Init]
`

### The issue:
Why can't this be easy? I'm getting to the point where I feel like, all the effort I've had to put in to make it work, then make it work again after an update breaks it, then trying to get a working config that doesn't chew up 8GB of RAM, actually runs quickly on startup - its like I'm on an a serial interface, the time its taking to reban or try and reban an already banned IP.

#### Steps to reproduce
Try and get a working config with firewalld, that doesn't ban on a per-port basis - if they are brute forcing ssh, then other ports should not be left open to them to use as another vector.

#### Expected behavior
Just work out of the box

#### Observed behavior
Granular to the point that it by default, closes only the vectors the attacker attacks, leaving open any other vector the attacker chooses to attack next time.
Taking a long time to reban what should be banned as part of a bulk ban on startup.
Considering Linux seems to need reboots as much as windows nowadays, its not very friendly.

#### Any additional information
Please implement a setup script which prompts for the firewall type, the behavior you want to apply, and have it work efficiently, so that IPs are not unbanned and rebanned on reboot, dont treat every IP in isolation, process on bulk.

I have only 556 IPs banned at the moment. If this was working properly, there would be well over 5 thousand.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
fail2ban.actions[1229]: NOTICE [sshd] Ban 37.59.42.112
fail2ban.filter[1229]: INFO [recidive] Found 37.59.42.112
fail2ban.actions[1229]: NOTICE [sshd] Ban 110.142.2.52
fail2ban.filter[1229]: INFO [recidive] Found 110.142.2.52
fail2ban.actions[1229]: NOTICE [recidive] 106.75.211.58 already banned
fail2ban.actions[1229]: NOTICE [sshd] Ban 123.59.182.194
fail2ban.filter[1229]: INFO [recidive] Found 123.59.182.194
fail2ban.actions[1229]: NOTICE [sshd] Ban 104.131.183.141
fail2ban.filter[1229]: INFO [recidive] Found 104.131.183.141
fail2ban.actions[1229]: NOTICE [sshd] Ban 117.149.2.38
fail2ban.filter[1229]: INFO [recidive] Found 117.149.2.38
fail2ban.actions[1229]: NOTICE [recidive] 80.211.159.146 already banned
fail2ban.actions[1229]: NOTICE [sshd] Ban 5.144.14.2
fail2ban.filter[1229]: INFO [recidive] Found 5.144.14.2
fail2ban.actions[1229]: NOTICE [sshd] Ban 188.187.55.243
fail2ban.filter[1229]: INFO [recidive] Found 188.187.55.243
fail2ban.actions[1229]: NOTICE [recidive] 114.115.132.154 already banned
fail2ban.actions[1229]: NOTICE [sshd] Ban 181.57.163.201
fail2ban.filter[1229]: INFO [recidive] Found 181.57.163.201
fail2ban.actions[1229]: NOTICE [sshd] Ban 93.99.147.90
fail2ban.filter[1229]: INFO [recidive] Found 93.99.147.90
fail2ban.actions[1229]: NOTICE [sshd] 123.150.200.121 already banned
fail2ban.actions[1229]: NOTICE [recidive] 86.105.49.170 already banned
```

Sorry if this sounds like a whine, really tired of trying to get that should be simple, to work.

**Comment by sedstr** [comment]
I can see its banning a lot of the IPs...
```
recidive (active)
  target: DROP
  icmp-block-inversion: no
  interfaces:
  sources: 187.111.253.194 188.166.78.118 189.36.202.190 191.96.249.128 193.169.80.252 193.201.224.199 193.213.204.133 194.24.228.93 195.154.60.103 195.22.126.43 197.101.10.155 197.224.116.247 198.100.28.118 198.199.71.245 198.50.179.83 199.195.251.179 2.178.177.81 201.155.194.157 202.106.204.226 202.54.249.131 203.123.36.134 208.108.197.141 210.73.40.61 211.110.140.39 211.141.154.230 211.224.22.35 211.23.154.14 212.20.102.40 212.224.88.142 212.237.47.187 212.237.47.6 212.237.59.87 217.11.34.47 218.147.99.252 218.38.121.17 218.4.104.194 220.171.43.5 223.197.184.24 23.224.254.138 23.225.23.170 27.151.73.62 31.208.16.100 31.46.27.15 36.89.48.50 37.49.224.165 37.49.226.21 37.49.226.22 40.125.162.239 41.138.51.69 41.84.21.158 42.112.195.46 42.112.80.75 42.225.252.25 43.242.84.52 45.55.236.152 46.101.136.151 46.160.144.250 46.246.35.236 46.249.78.142 5.135.161.94 5.166.138.71 5.188.203.131 5.188.9.75 54.38.21.172 58.123.212.180 58.52.158.120 59.46.185.19 59.9.93.33 61.146.51.11 61.160.26.34 61.181.65.10 66.70.187.233 69.162.78.51 72.49.150.68 80.211.11.250 80.211.19.237 80.70.73.158 80.82.77.38 81.50.4.119 82.146.62.2 82.200.65.218 83.16.14.107 84.127.215.52 85.148.142.15 87.252.190.178 88.120.195.49 88.127.227.155 88.171.160.112 88.249.201.225 89.165.141.44 92.53.66.111 92.63.197.50 93.203.80.232 93.78.29.185 94.156.23.246 187.108.37.126 199.47.173.6 201.231.247.226 218.235.90.142 24.72.6.171 31.170.57.216 37.191.196.1 42.7.26.15 46.243.189.112 60.250.37.158 61.164.67.36 73.136.216.106 101.81.104.123 103.47.134.48 104.25.54.31 104.41.50.64 1.10.187.62 111.248.131.71 111.253.232.84 112.184.105.86 115.55.100.151 115.63.205.52 116.241.187.183 116.49.115.170 118.171.56.66 118.232.197.102 119.201.58.149 119.236.186.70 119.237.153.156 119.237.200.73 121.126.152.10 121.126.233.36 121.185.120.148 121.190.136.127 121.254.86.76 123.12.179.62 123.140.47.222 123.194.181.70 124.235.183.216 124.6.27.193 125.148.251.133 125.59.42.110 125.77.30.10 129.21.199.101 13.32.121.224 134.255.252.231 1.36.224.80 138.118.177.101 138.118.178.36 138.118.179.10 138.118.179.69 138.186.76.209 138.219.228.39 142.111.192.125 142.4.196.36 142.4.200.54 14.33.138.42 14.38.0.189 144.202.13.166 144.217.158.169 144.217.228.79 144.217.28.69 144.217.58.209 144.217.89.103 145.239.64.181 149.202.38.124 14.94.90.184 151.80.108.156 151.80.230.107 158.69.5.190 160.33.32.131 1.64.12.89 164.132.241.208 167.114.94.24 173.0.84.225 173.0.84.226 173.0.84.227 173.0.84.228 173.245.59.118 175.180.240.210 175.6.26.203 176.221.120.83 176.226.182.253 180.70.127.136 183.101.45.197 183.129.160.229 183.143.81.213 183.179.174.146 185.175.42.32 185.203.72.8 185.239.237.144 185.45.165.251 185.66.84.217 188.165.197.115 188.169.3.226 192.168.2.10 192.5.5.241 195.154.251.115 195.70.63.29 196.196.13.66 198.27.92.1 200.111.101.6 200.94.252.129 201.139.204.191 209.6.203.104 211.25.101.194 213.112.130.141 213.131.59.254 217.148.84.184 217.169.192.11 217.218.209.242 218.204.102.204 220.119.119.79 220.80.116.149 220.86.21.144 221.127.68.73 222.137.205.200 223.16.101.84 223.17.138.152 223.18.118.40 223.18.207.246 24.57.152.152 27.220.176.78 27.41.67.89 27.41.71.134 31.28.7.251 35.194.213.125 35.201.196.100 36.233.45.76 36.237.91.201 39.135.17.28 39.135.17.29 39.135.17.30 39.135.17.31 39.135.17.32 39.135.17.33 39.135.17.34 39.135.17.35 39.135.17.36 39.135.17.37 39.135.17.38 39.135.17.39 39.135.17.40 39.135.17.41 39.135.17.42 39.135.17.43 41.76.242.118 45.227.158.193 45.7.14.45 45.7.15.34 46.174.54.48 46.174.54.76 46.243.189.101 47.20.249.91 49.195.121.239 49.199.151.119 49.238.152.23 49.254.165.133 50.116.113.64 5.150.212.35 52.233.180.81 5.30.19.139 54.37.218.163 5.79.65.141 58.108.115.180 58.153.153.161 58.153.5.5 58.153.79.103 58.242.27.204 59.52.27.140 59.56.78.21 61.140.126.90 61.77.52.166 62.129.222.89 66.135.215.101 66.135.215.117 66.6.166.174 74.87.88.130 77.233.7.3 78.155.198.3 81.15.212.143 85.152.70.93 85.190.156.89 89.34.99.116 89.46.123.18 90.240.96.200 91.134.107.160 91.232.105.229 91.240.164.151 92.63.197.40 93.144.75.80 95.165.158.80 95.181.116.77 95.68.138.195 95.96.215.20 96.30.103.154 98.14.224.16 1.119.145.66 1.202.136.28 1.234.4.14 101.236.61.35 101.89.184.52 103.207.39.234 103.210.135.136 103.27.239.27 103.28.219.152 103.56.239.157 103.70.223.14 103.79.143.189 103.89.89.18 104.192.1.30 104.36.166.222 105.159.249.14 106.12.25.220 106.120.105.21 106.200.238.155 106.242.65.122 106.75.135.147 106.75.151.101 108.175.11.165 109.111.180.145 109.121.193.20 109.230.253.225 109.245.221.126 109.50.162.43 111.200.217.235 111.7.177.239 112.144.41.186 112.171.69.24 112.214.162.247 112.6.224.2 112.91.98.194 113.108.72.2 113.161.91.33 114.115.132.154 114.115.132.164 114.115.132.255 114.115.133.122 114.115.144.83 114.115.164.144 114.115.172.44 114.115.181.113 114.115.182.97 114.115.183.225 114.115.215.205 114.115.215.246 114.207.113.80 114.235.32.218 114.67.75.149 115.159.202.216 115.159.71.44 115.231.9.131 115.71.232.217 116.125.224.129 116.196.87.93 116.255.191.99 117.107.252.24 117.52.74.162 117.53.227.73 118.244.238.4 118.34.51.141 118.68.134.219 118.68.144.41 118.89.178.26 118.89.227.26 118.98.68.102 119.192.13.115 119.193.140.211 119.27.187.124 119.38.171.2 120.236.128.53 120.52.139.69 121.137.9.214 121.140.142.231 121.15.166.225 121.201.34.35 121.52.150.53 122.112.198.205 122.112.239.167 122.112.239.62 122.112.239.87 122.112.239.89 122.114.174.56 122.154.134.38 122.248.37.41 123.150.200.121 123.59.135.58 123.7.124.12 124.158.124.9 125.212.228.165 125.212.233.81 125.212.249.115 125.212.253.80 126.150.95.59 128.199.77.138 128.199.91.171 13.126.235.110 13.231.104.29 13.92.225.98 131.255.143.244 133.18.57.73 134.255.214.140 137.175.209.8 137.74.29.29 138.197.201.169 138.197.79.125 138.68.155.108 139.159.209.232 139.159.228.234 139.159.232.145 139.159.233.246 139.159.235.43 139.159.237.120 139.159.237.18 139.159.238.103 139.217.202.178 139.217.202.77 139.59.19.109 139.59.244.27 139.59.34.69 139.59.38.150 139.59.45.192 139.59.81.69 139.99.9.63 14.141.68.67 14.23.77.154 14.33.133.188 14.49.130.3 140.138.77.170 141.105.64.232 145.249.106.78 149.154.65.232 151.248.182.38 153.149.230.33 154.127.139.214 155.4.122.210 157.192.72.37 157.52.167.125 158.69.159.232 159.203.191.201 159.65.204.210 159.65.247.36 159.89.226.43 159.89.234.208 161.0.118.138 161.139.115.25 162.209.156.96 162.209.158.248 162.243.86.122 162.244.15.147 163.172.144.137 163.172.20.129 164.163.99.10 165.227.104.194 165.227.161.170 167.114.11.120 167.114.206.246 167.99.9.64 168.227.0.197 168.70.37.89 17.179.250.135 170.78.3.26 171.248.164.211 171.36.209.48 172.104.74.49 172.246.83.92 172.96.160.28 173.249.15.111 173.249.29.133 174.56.206.23 175.110.107.250 175.110.162.173 175.204.125.29 175.25.48.249 176.107.130.200 176.115.15.62 176.222.128.39 177.103.181.101 177.70.21.252 177.85.103.72 178.157.201.146 178.48.146.234 178.62.229.23 179.113.255.22 179.185.43.186 179.189.39.99 180.100.217.67 180.168.12.29 180.250.19.128 180.250.247.43 181.111.193.251 181.214.87.222 181.50.122.237 182.100.67.52 182.150.37.48 182.160.115.155 182.18.162.136 182.40.152.51 182.61.108.55 182.93.83.15 183.236.36.159 183.57.72.51 183.6.159.187 185.143.223.206 185.150.189.94 185.173.226.39 185.212.200.122 185.222.211.30 185.228.80.42 185.243.112.65 185.85.207.164 186.227.231.249 188.165.68.135 189.201.158.18 189.254.33.157 190.147.88.247 192.169.155.230 192.210.198.18 193.106.147.166 193.227.46.66 193.70.90.250 194.182.73.196 195.22.126.105 195.36.154.98 198.100.28.46 198.100.29.107 198.100.29.116 198.16.50.136 198.16.51.56 198.2.138.147 201.147.183.55 202.131.227.51 202.138.233.92 203.154.243.50 203.218.84.14 207.107.67.114 207.204.204.84 210.223.53.118 211.196.157.28 212.237.53.29 216.172.160.161 216.187.82.76 216.245.194.116 216.245.222.250 217.182.230.40 217.67.26.154 218.90.150.118 220.245.146.47 220.68.231.105 221.146.5.81 222.168.152.216 223.240.215.21 223.88.3.47 23.224.120.196 23.92.25.245 23.94.92.11 27.116.21.218 27.191.235.90 31.7.144.145 35.160.134.253 35.197.233.81 36.227.233.72 36.66.164.143 36.80.34.225 38.108.53.157 41.223.142.211 41.224.62.70 43.230.4.64 45.242.16.8 45.33.12.103 45.33.60.57 45.40.138.145 45.56.120.239 46.246.40.179 49.156.148.212 49.206.196.114 5.101.0.51 5.101.40.10 5.188.203.113 5.255.178.59 5.36.224.39 50.116.49.119 51.15.216.235 51.254.47.198 52.15.223.221 52.230.71.112 52.66.15.235 54.37.131.35 54.37.158.40 54.37.17.179 54.38.136.158 59.28.218.38 59.7.96.57 60.174.165.20 60.221.230.2 60.250.168.200 60.30.160.110 60.49.12.81 61.105.167.11 61.177.172.233 61.78.248.54 62.82.203.212 63.143.44.46 68.64.168.126 75.136.156.134 77.82.90.234 77.9.124.243 78.41.207.224 79.41.237.100 80.152.174.52 80.211.10.127 80.211.14.161 80.211.159.146 81.130.146.18 82.112.32.45 82.200.205.71 82.202.249.153 83.240.242.22 85.199.232.4 86.105.49.170 87.15.179.71 87.252.190.50 88.26.245.85 88.87.202.71 91.121.105.20 91.121.77.149 91.135.20.33 91.136.160.87 91.137.19.28 91.186.250.4 91.234.97.158 91.236.178.157 92.226.251.166 92.9.100.128 93.147.131.23 94.153.194.22 94.177.164.232 94.20.64.202 94.23.154.207 94.56.214.166 95.147.186.12 95.38.15.86 110.10.189.182 158.36.13.34 195.178.222.29 62.241.131.10 66.44.48.133 27.211.250.235 119.193.140.221 31.168.215.228 61.177.172.234 186.75.76.73 159.226.43.35 112.161.220.151 37.59.42.112 110.142.2.52 123.59.182.194 117.149.2.38 5.144.14.2 188.187.55.243 181.57.163.201 93.99.147.90 166.62.41.196 103.231.218.254 202.129.16.124 139.99.122.129 52.187.36.225 201.217.157.83 77.246.229.48 103.26.99.120 180.250.210.133 201.139.110.34 108.56.133.70 125.212.207.204 183.82.0.15 121.28.103.135 180.87.136.248 119.29.15.72
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

drop (active)
  target: DROP
  icmp-block-inversion: no
  interfaces:
  sources: 202.29.243.107 203.190.163.125 209.58.86.168 219.139.39.109 46.105.20.171 61.153.56.30 91.221.6.229 61.177.172.231 1.245.203.113 1.234.79.66 103.15.74.82 106.75.211.58 103.207.36.95 112.148.101.46 110.163.131.235 115.146.127.81 103.200.22.113 117.66.243.77 118.184.53.50 1.234.56.175 105.226.108.53 123.207.159.55 122.165.203.33 104.236.102.142 117.218.85.28 103.29.16.18 115.159.105.14 118.36.193.215 110.10.174.179 138.68.149.171 103.44.167.204 103.99.0.223 1.85.18.88 106.51.72.240 103.68.36.57 120.132.114.147 115.249.100.66 103.26.14.92 194.78.59.98 103.20.149.252 138.68.7.146 193.70.85.206 116.48.130.162 196.216.8.110 185.45.163.238 194.225.229.201 128.143.100.126 110.10.189.108 119.79.224.90 103.99.0.132 119.235.21.178 177.53.41.199 216.245.215.98 195.137.185.77 112.161.187.208 179.228.242.120 175.117.145.239 110.10.129.226 171.244.34.34 186.46.90.101 156.204.181.129 210.121.196.10 202.104.149.55 23.242.211.142 187.72.107.130 103.207.39.175 185.143.223.4 41.73.252.236 112.220.201.150 169.255.104.20 180.168.36.170 203.217.56.210 123.157.138.165 191.96.249.80 189.135.213.47 223.27.235.41 103.99.2.192 59.17.249.180 188.166.216.84 178.19.130.191 39.109.10.138 128.199.35.247 49.248.152.178 152.249.13.175 106.51.5.129 58.185.176.108 37.252.64.178 69.181.209.51 182.48.117.84 51.255.166.189 37.59.54.165 156.209.202.140 60.190.104.228 59.147.36.54 119.29.154.229 218.65.30.25 180.101.145.87 210.182.116.102 121.28.142.44 58.217.157.209 168.227.95.248 188.23.44.112 138.68.75.179 125.212.248.37 114.70.193.188 61.138.232.34 118.68.134.145 114.200.4.207 119.29.27.246 104.131.183.141 195.219.9.72 122.2.223.242 92.222.119.202 5.196.65.134
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
but there are others which the rules seem to have problems with - I'm interpreting this as the IP's not being able to be put into two zones which target the drop zone...

```
Mar 20 07:29:03 host.mydomain.com fail2ban.filter[1229]: INFO [recidive] Found 61.177.172.231
Mar 20 07:29:03 host.mydomain.com fail2ban.filter[1229]: INFO [recidive] Found 61.177.172.231
Mar 20 07:29:04 host.mydomain.com fail2ban.actions[1229]: NOTICE [recidive] Ban 61.177.172.231
Mar 20 07:29:11 host.mydomain.com fail2ban.action[1229]: ERROR firewall-cmd --change-source=61.177.172.231 --zone=recidive && firewall-cmd --runtime-to-permanent -- stdout: 'success\n'
Mar 20 07:29:11 host.mydomain.com fail2ban.action[1229]: ERROR firewall-cmd --change-source=61.177.172.231 --zone=recidive && firewall-cmd --runtime-to-permanent -- stderr: '\x1b[91mError: RT_TO_PERM_FAILED\x1b[00m\n'
Mar 20 07:29:11 host.mydomain.com fail2ban.action[1229]: ERROR firewall-cmd --change-source=61.177.172.231 --zone=recidive && firewall-cmd --runtime-to-permanent -- returned 31
Mar 20 07:29:11 host.mydomain.com fail2ban.actions[1229]: ERROR Failed to execute ban jail 'recidive' action 'firewallcmd-custom-recidive' info 'CallingMap({'ipjailmatches': <function <lambda> at 0x181e0c8>, 'matches': '2018-03-13T07:36:49.725202host.mydomain.com fail2ban.actions[1201]: NOTICE [sshd] Ban 61.177.172.231\n2018-03-13T07:36:50.068686host.mydomain.com fail2ban.actions[1201]: NOTICE [sshd-ddos] Ban 61.177.172.231', 'ip': '61.177.172.231', 'ipmatches': <function <lambda> at 0x181e050>, 'ipfailures': <function <lambda> at 0x181e140>, 'time': 1521545344.487912, 'failures': 2, 'ipjailfailures': <function <lambda> at 0x181e1b8>})': Error banning 61.177.172.231
Mar 20 07:29:24 host.mydomain.com firewalld[779]: ERROR: ZONE_CONFLICT: 61.177.172.231
Mar 20 07:29:24 host.mydomain.com firewalld[779]: WARNING: Runtime To Permanent failed on zone 'drop': org.fedoraproject.FirewallD1.Exception: ZONE_CONFLICT: 61.177.172.231
Mar 20 07:29:31 host.mydomain.com fail2ban.filter[1229]: INFO [recidive] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [recidive] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231
Mar 20 07:30:32 host.mydomain.com fail2ban.filter[1229]: INFO [sshd] Found 61.177.172.231

```
