### ISSUE TITLE
fail2ban host - bitwarden docker - no valid date/time found

### ISSUE THREAD

**Issue by Ylawy** [fail2ban/fail2ban#2772]
- Fail2Ban version (0.10.2):
- Ubuntu 18.04.4 LTS: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

fail2ban is not able to block IP even though it found a match. I looked into the timezone issue but bitwarden docker container and local host have the same time. I'm no regex expert and don't know if this ""time":"2020-07-07T14:15:02.590956303Z" in my log files might be the culprit.
fail2ban is installed on host. Bitwarden_RS is installed via docker with traefik as reverse proxy in front.

Here are my fail2ban logs:

```
2020-07-07 16:15:02,603 fail2ban.filter         [30090]: WARNING Found a match for '{"log":"[2020-07-07 16:15:02][error][ERROR] Username or password is incorrect. Try again. IP: 141.xxx.xxx.xxx. Username: der@eedud3edd.com.\\n","stream":"stdout","time":"2020-07-07T14:15:02.590956303Z"}' but no valid date/time found for '{"log":"[2020-07-07 16:15:02][error][ERROR] Username or password is incorrect. Try again. IP: 141.xxx.xxx.xxx. Username: der@eedud3edd.com.\\n","stream":"stdout","time":"2020-07-07T14:15:02.590956303Z"}'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
2020-07-07 16:15:06,751 fail2ban.filter         [30090]: WARNING Found a match for '{"log":"[2020-07-07 16:15:06][error][ERROR] Username or password is incorrect. Try again. IP: 141.xxx.xxx.xxx. Username: der@eedud3eeedd.com.\\n","stream":"stdout","time":"2020-07-07T14:15:06.706503139Z"}' but no valid date/time found for '{"log":"[2020-07-07 16:15:06][error][ERROR] Username or password is incorrect. Try again. IP: 141.xxx.xxx.xxx. Username: der@eedud3eeedd.com.\\n","stream":"stdout","time":"2020-07-07T14:15:06.706503139Z"}'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```
Here is from my /jail.d/bitwarden.local:

```[bitwarden]
enabled = true
port = 80,443
filter = bitwarden
action = iptables-allports[name=Bitwarden]
logpath = /var/lib/docker/containers/*/*-json.log
maxretry = 5
bantime = 14400
findtime = 14400
```
Here is from my /filter.d/bitwarden.local:

```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\. Username:.*$
ignoreregex =
```

Here is from my /action.d/iptables-common.local:
```
[Init]
blocktype = DROP
[Init?family=inet6]
blocktype = DROP
```

Here is from my bitwarden docker-compose.yml:
```
version: '2'
services:
  bitwarden:
   image: bitwardenrs/server:latest
   container_name: bitwardenrs
   restart: unless-stopped
   volumes:
     - /volume1/bwdata:/data/
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
   ports:
     - 80:80
   environment:
     - TZ=Europe/Berlin
   labels:
     - traefik.enable=true
     - traefik.http.routers.bitwarden.rule=Host(`url`)
     - traefik.http.routers.bitwarden.entrypoints=web
   networks:
     - web

networks:
    web:
        external:
            name: web
```
