### ISSUE TITLE
[BR]: Fail2Ban does not detect newly created log files (e.g. Jellyfin)

### ISSUE THREAD

**Issue by MartenBE** [fail2ban/fail2ban#3100]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : Fedora 34
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Jellyfin creates a log file each day. However, fail2ban only seems to detect the logfiles when fail2ban is (re)started. This means that the next day and the days from there on, the Jellyfin instance is unprotected as the new log files aren't processed.
Some tutorials mentioning this problem suggest restarting the fail2ban service using cron [1], but this doesn't seem like the best approach to me? Shouldn't fail2ban detect when new files are created that match the given regexp?

[1] https://terminal.ovh/2020/08/fail2ban-does-not-pick-up-new-logfiles-created-every-day/

#### Steps to reproduce

Start fail2ban (here on 13 September 2021)

```
$ fail2ban-client status jellyfin
Status for the jail: jellyfin
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210911.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210912.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210913.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

#### Expected behavior

On 15 September 2021

```
$ fail2ban-client status jellyfin
Status for the jail: jellyfin
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210911.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210912.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210913.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210914.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210915.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

#### Observed behavior

On 15 September 2021

```
$ fail2ban-client status jellyfin
Status for the jail: jellyfin
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210911.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210912.log /home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210913.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

Fail2ban has not detected `/home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210914.log` `/home/user/server/docker/jellyfin/.files-jellyfin/log/log_20210915.log`

#### Any customizations done to /etc/fail2ban/ configuration

jail.conf
```
[jellyfin]
enabled = true
port = 80,443,9861
protocol = tcp
filter = jellyfin
logpath = /home/user/server/docker/jellyfin/.files-jellyfin/log/log_*.log
```

filter.d/jellyfin.conf
```
[Definition]
failregex = ^(?:\[\]\s+)?\[INF\] Authentication request for "[^"]*" has been denied \(IP: "<HOST>"\)\.$
```

docker-compose.yml
```
version: "3"

services:
    jellyfin:
        image: jellyfin/jellyfin
        network_mode: "host"
        volumes:
            - .files-jellyfin/config:/config
            - .files-jellyfin/cache:/cache
            - .files-jellyfin/log:/config/log
            - ${MOVIES_FOLDER}:/movies
            - ${SERIES_FOLDER}:/series
            - ${BOOKS_FOLDER}:/books
            - ${COMICS_FOLDER}:/comics
            - ${NEW_FOLDER}:/new
```
