### ISSUE TITLE
Fail2Ban docker works only on startup for Ms Sql Log, then stops monitoring log file changes

### ISSUE THREAD

**Issue by haroldcris** [fail2ban/fail2ban#3779]
### Environment:
simple jail.local settings

jail.d/jail.local
```
[mssql-auth]
enabled = true
bantime = 60
maxretry = 3
findtime = 200

```

docker-compose file
```
services:
  db1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MsSql2019
    #user: root
    environment:
      ACCEPT_EULA: "Y"      
      MSSQL_SA_PASSWORD: "password"
      MSSQL_AGENT_ENABLED: "true"
      TZ: Asia/Manila
    ports:
      - 1433:1433
    volumes:
      - ./mssql/log:/var/opt/mssql/log

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/data:/data
      - ./fail2ban/log:/var/log:ro
      - ./mssql/log:/var/opt/mssql/log:ro
    depends_on:
      - db1      
    environment:
      TZ: "Asia/Manila"
    network_mode: "service:db1" 
```

### The issue:
after [maxretry] failed attempt, fail2ban does NOT ban the ip address. You have to restart the fail2ban container to reflect the changes.

#### Steps to reproduce
1. Run the docker compose up
2. Try to login with invalid credential to mssql, 4 times.
3. Check the fail2ban status by using the command
`docker exec -it fail2ban fail2ban-client status mssql-auth`
nothing happens.
4. Restart the fail2ban container, it reads the log file and bans the Ip correctly.
5. After starting, it stops monitoring changes to log file. 

#### Expected behavior
Fail2ban should ban the Ip Address after [maxretry] failed attempt without restarting the container.

#### Observed behavior
After [maxretry] failed attempt, you have to restart the fail2ban container, then the IP will be added to ban ip list.
No problem with unblocking ip, it automatically unblocks the Ip after bantime expires.
